### ISSUE TITLE
Find data for milestone 1

### ISSUE THREAD

**Issue by jgurganu** [fdac20/BikeShare#2]

**Comment by michael-cox** [comment]
Here are my links:
Title: Kaggle Bike Share Trip Data
	Description: Kaggle San Francisco bike share data
	License: NA
	URL(s):
['https://www.kaggle.com/benhamner/sf-bay-area-bike-share/metadata']

Title: Divvy Bike Shares Trip Data
	Description: Divvy Bike Shares in Chicago
	License: Divvy Data License Agreement
	URL(s):
['https://www.divvybikes.com/system-data']

Title: Citi Bike Share Trip Data
	Description: Citi Bike Share in NYC
	License: NYCBS Data Use Policy
	URL(s):
['https://www.citibikenyc.com/system-data']

Title: Capital Bike Share Trip Data
	Description: Capital Bike Share Trip Data in Washington DC
	License: Capital Bikeshare Data License Agreement
	URL(s):
['https://www.capitalbikeshare.com/system-data']

Title: Uber Trip Data
	Description: Uber Trip Data NYC 2014
	License: NA
	URL(s):
['https://github.com/fivethirtyeight/uber-tlc-foil-response']

Title: Lyft Self Driving Car Data
	Description: Lyft Self Driving Car Data
	License: Unknown
	URL(s):
['https://self-driving.lyft.com/level5/data/']

Title: RideAustin Trip Data
	Description: RideAustin Trip Data Austin 2016-2017
	License: NA
	URL(s):
['https://public.opendatasoft.com/explore/dataset/rideaustin/information/']

Title: Uber Movement Trip Data
	Description: Uber Movement Trip Data (divided by city)
	License: Unknown
	URL(s):
['https://data.world/rmiller107/travel-time-uber-movement', 'https://movement.uber.com/?lang=en-US']

Title: Uber Active Users
	Description: Uber's Active users by month from 2017 to 2020 worldwide
	License: Unknown
	URL(s):
['https://www.statista.com/statistics/833743/us-users-ride-sharing-services/']

Title: Leading Ride-Hailing Companies US 2017-2020
	Description: Leading Ride Hailing Companies US 2017-2020
	License: Unknown
	URL(s):
['https://www.statista.com/statistics/910704/market-share-of-rideshare-companies-united-states/']

Title: Uber/Lyft Average Cost Per Ride
	Description: Uber/Lyft average quarterly cost per ride 2017-2019
	License: NA
	URL(s):
['https://www.statista.com/statistics/890167/average-cost-per-ride-ridesharing-united-states/']

Title: Ride Sharing Use Demographics
	Description: Percentage of respondents in the U.S. using ride sharing in 2016, by demographic group
	License: NA
	URL(s):
['https://www.statista.com/statistics/720636/consumers-who-use-ride-sharing-by-demographic-group/']

Title: Average revenue per user in the online Ride Sharing market in Switzerland from 2017 to 2023
	Description: Average revenue per user in the online Ride Sharing market in Switzerland from 2017 to 2023
	License: NA
	URL(s):
['https://www.statista.com/forecasts/891596/arpu-in-the-online-ride-sharing-market-in-switzerland']

Title: Share of Uber's users in the U.S. ride sharing market in Q1 2017, by gender
	Description: Share of Uber's users in the U.S. ride sharing market in Q1 2017, by gender
	License: NA
	URL(s):
['https://www.statista.com/statistics/822947/us-ride-sharing-uber-users-gender/']

Title: Most popular ride sharing service among users in Vietnam in 2018
	Description: Most popular ride sharing service among users in Vietnam in 2018
	License: NA
	URL(s):
['https://www.statista.com/statistics/1003417/vietnam-most-used-ride-sharing-service/']

Title: Ride sharing usage by brand in Spain 2020
	Description: Which of these ride sharing providers have you used in the past 12 months?
	License: NA
	URL(s):
['https://www.statista.com/forecasts/1001507/ride-sharing-usage-by-brand-in-spain']

Title: Ride sharing usage by brand in Italy 2020
	Description: Which of these ride sharing providers have you used in the past 12 months?
	License: NA
	URL(s):
['https://www.statista.com/forecasts/1000739/ride-sharing-usage-by-brand-in-italy']

Title: Ride sharing usage by brand in Austria 2020
	Description: Which of these ride sharing providers have you used in the past 12 months?
	License: NA
	URL(s):
['https://www.statista.com/forecasts/1001276/ride-sharing-usage-by-brand-in-austria']

Title: Distribution of ride-sharing market in China Q4 2018, by company
	Description: Distribution of ride-sharing market in China Q4 2018, by company
	License: NA
	URL(s):
['https://www.statista.com/statistics/1049740/china-distribution-of-ride-sharing-market-by-company/', 'https://multimedia.scmp.com/infographics/china-internet/pdf/china_internet_report_2019.pdf']

Title: Ride sharing usage by brand in Canada 2020
	Description: Which of these ride sharing providers have you used in the past 12 months?
	License: NA
	URL(s):
['https://www.statista.com/forecasts/998574/ride-sharing-usage-by-brand-in-canada']

I don't think we will really be fetching data like I said in the milestone. Instead, I think I will work on compiling similar data into one CSV or something.

**Comment by jgurganu** [comment]
[BikeShare datasets.pdf](https://github.com/fdac20/BikeShare/files/5355593/BikeShare.datasets.pdf)

Additional datasets
